# Generated by Django 5.2.7 on 2025-11-04 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número da Matrícula')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível para uso')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_utilizacao', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matricula_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
            },
        ),
    ]
